import { Agent, LogEntry } from "./types"

// Mock agents for development/testing
export const mockAgents: Agent[] = [
  {
    id: "agent-1",
    name: "Orchestrator-Prime",
    type: "orchestrator",
    status: "running",
    model: "claude-sonnet-4-20250514",
    currentTask: "Coordinating dashboard implementation",
    taskId: "task-1",
    progress: 65,
    tokensUsed: 45000,
    maxTokens: 100000,
    createdAt: new Date(Date.now() - 3600000),
    projectId: "project-1",
    skills: ["coordination", "task-delegation", "workflow-management"],
  },
  {
    id: "agent-2",
    name: "Coder-Alpha",
    type: "coder",
    status: "running",
    model: "claude-sonnet-4-20250514",
    currentTask: "Implementing AgentPanel component",
    taskId: "task-2",
    progress: 85,
    tokensUsed: 32000,
    maxTokens: 100000,
    createdAt: new Date(Date.now() - 1800000),
    projectId: "project-1",
    skills: ["code-generation", "refactoring", "debugging"],
  },
  {
    id: "agent-3",
    name: "Researcher-Beta",
    type: "researcher",
    status: "paused",
    model: "gpt-4o",
    currentTask: "Gathering API documentation",
    taskId: "task-3",
    progress: 40,
    tokensUsed: 15000,
    maxTokens: 50000,
    createdAt: new Date(Date.now() - 7200000),
    projectId: "project-1",
    skills: ["web-search", "documentation", "analysis"],
  },
  {
    id: "agent-4",
    name: "Tester-Gamma",
    type: "tester",
    status: "idle",
    model: "claude-sonnet-4-20250514",
    progress: 0,
    tokensUsed: 5000,
    maxTokens: 50000,
    createdAt: new Date(Date.now() - 900000),
    skills: ["test-generation", "test-execution", "coverage-analysis"],
  },
  {
    id: "agent-5",
    name: "Planner-Delta",
    type: "planner",
    status: "error",
    model: "claude-opus-4-20250514",
    currentTask: "Creating sprint plan",
    taskId: "task-5",
    progress: 25,
    tokensUsed: 95000,
    maxTokens: 100000,
    createdAt: new Date(Date.now() - 5400000),
    projectId: "project-2",
    skills: ["task-planning", "estimation", "prioritization"],
  },
  {
    id: "agent-6",
    name: "Reviewer-Epsilon",
    type: "reviewer",
    status: "running",
    model: "claude-sonnet-4-20250514",
    currentTask: "Reviewing PR #42",
    taskId: "task-6",
    progress: 55,
    tokensUsed: 28000,
    maxTokens: 75000,
    createdAt: new Date(Date.now() - 2700000),
    projectId: "project-1",
    skills: ["code-review", "best-practices", "security-audit"],
  },
]

// Mock log entries for development/testing
export const mockLogs: LogEntry[] = [
  {
    id: "log-1",
    timestamp: new Date(Date.now() - 60000),
    level: "info",
    agentId: "agent-1",
    agentName: "Orchestrator-Prime",
    message: "Starting workflow coordination for dashboard project",
  },
  {
    id: "log-2",
    timestamp: new Date(Date.now() - 55000),
    level: "debug",
    agentId: "agent-2",
    agentName: "Coder-Alpha",
    message: "Analyzing component structure requirements",
  },
  {
    id: "log-3",
    timestamp: new Date(Date.now() - 50000),
    level: "info",
    agentId: "agent-1",
    agentName: "Orchestrator-Prime",
    taskId: "task-1",
    message: "Delegating AgentPanel implementation to Coder-Alpha",
  },
  {
    id: "log-4",
    timestamp: new Date(Date.now() - 45000),
    level: "info",
    agentId: "agent-2",
    agentName: "Coder-Alpha",
    taskId: "task-2",
    message: "Beginning component implementation",
  },
  {
    id: "log-5",
    timestamp: new Date(Date.now() - 40000),
    level: "debug",
    agentId: "agent-2",
    agentName: "Coder-Alpha",
    message: "Creating TypeScript interfaces for Agent types",
  },
  {
    id: "log-6",
    timestamp: new Date(Date.now() - 35000),
    level: "warn",
    agentId: "agent-3",
    agentName: "Researcher-Beta",
    message: "Rate limit approaching on external API",
  },
  {
    id: "log-7",
    timestamp: new Date(Date.now() - 30000),
    level: "info",
    agentId: "agent-3",
    agentName: "Researcher-Beta",
    message: "Pausing research to avoid rate limiting",
  },
  {
    id: "log-8",
    timestamp: new Date(Date.now() - 25000),
    level: "debug",
    agentId: "agent-2",
    agentName: "Coder-Alpha",
    message: "Implementing AgentCard component with status indicators",
  },
  {
    id: "log-9",
    timestamp: new Date(Date.now() - 20000),
    level: "error",
    agentId: "agent-5",
    agentName: "Planner-Delta",
    message: "Token limit exceeded while generating sprint plan",
  },
  {
    id: "log-10",
    timestamp: new Date(Date.now() - 15000),
    level: "info",
    agentId: "agent-6",
    agentName: "Reviewer-Epsilon",
    message: "Starting code review for PR #42",
  },
  {
    id: "log-11",
    timestamp: new Date(Date.now() - 10000),
    level: "debug",
    agentId: "agent-6",
    agentName: "Reviewer-Epsilon",
    taskId: "task-6",
    message: "Analyzing code changes in 12 files",
  },
  {
    id: "log-12",
    timestamp: new Date(Date.now() - 5000),
    level: "info",
    agentId: "agent-2",
    agentName: "Coder-Alpha",
    taskId: "task-2",
    message: "AgentPanel component implementation 85% complete",
  },
  {
    id: "log-13",
    timestamp: new Date(),
    level: "info",
    agentId: "agent-1",
    agentName: "Orchestrator-Prime",
    message: "All agents operating within expected parameters",
  },
]

// Mock projects for testing spawn modal
export const mockProjects = [
  { id: "project-1", name: "MoltBot Dashboard" },
  { id: "project-2", name: "API Integration" },
  { id: "project-3", name: "Documentation" },
]

// Mock tasks for testing spawn modal
export const mockTasks = [
  { id: "task-1", name: "Implement agent monitoring" },
  { id: "task-2", name: "Create log viewer component" },
  { id: "task-3", name: "Add real-time updates" },
  { id: "task-4", name: "Write unit tests" },
]
